name = "trading-bot"
main = "workers/api/src/index.ts"
compatibility_date = "2024-04-03"

[vars]
ENVIRONMENT = "development"
CTRADER_REDIRECT_URI = "http://localhost:8787/oauth/callback"

[[d1_databases]]
binding = "DB"
database_name = "trading-bot"
database_id = "5e0c9977-e7b9-40a0-b6db-5032c2f863bf"
migrations_dir = "database/migrations"

[[durable_objects.bindings]]
name = "CTRADER_ACCOUNT_DO"
class_name = "CTraderAccount"


[[migrations]]
tag = "v1"
new_sqlite_classes = ["CTraderAccount"]

[ai]
binding = "AI"
